index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: [GET]

contacts:
    path: /contacts
    controller: App\Controller\DefaultController::contacts
    methods: [GET]

post_view:
    path: /post/view/{id}
    controller: App\Controller\PostController::view
    methods: [GET]

# Admin panel
admin_home:
    path: /admin
    controller: App\Controller\Admin\DefaultController::index
    methods: [GET]

greeflas_newsletter:
    resource: '@GreeflasNewsletterBundle/Resources/config/routes.yaml'
