index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: [GET]

contacts:
    path: /contacts
    controller: App\Controller\DefaultController::contacts
    methods: [GET]
